const examples = {
  sumLoop: {
    name: "Loop de Soma",
    codeLines: [
      "1   int soma = 0;",
      "2   int vezes = 3;",
      "3   ",
      "4   for(int i = 1; i <= vezes; i++) {",
      '5       printf("Volta %d\\n", i);',
      "6       soma = soma + i;",
      "7   }",
      "8   ",
      '9   printf("Soma total: %d\\n", soma);',
      "10  ",
      "11  return soma;",
    ],
    steps: [
      {
        line: 0,
        action: "int soma = 0;",
        desc: "Declara variável 'soma' e inicializa com 0 na memória RAM",
        vars: { soma: 0 },
      },
      {
        line: 1,
        action: "int vezes = 3;",
        desc: "Declara variável 'vezes' e inicializa com 3 (limite do loop)",
        vars: { vezes: 3, soma: 0 },
      },
      {
        line: 3,
        action: "Preparando para entrar no loop FOR",
        desc: "O processador avalia a condição de início do loop",
        vars: { vezes: 3, soma: 0, i: null },
      },
      {
        line: 4,
        action: "i = 1 (inicialização do FOR)",
        desc: "PC aponta para linha 4. Variável i recebe valor 1",
        vars: { vezes: 3, soma: 0, i: 1 },
      },
      {
        line: 4,
        action: "Teste i <= vezes? (1 <= 3)",
        desc: "Comparação: i(1) é menor ou igual a vezes(3)? VERDADEIRO → entra no loop",
        vars: { vezes: 3, soma: 0, i: 1 },
      },
      {
        line: 5,
        action: 'printf("Volta 1\\n")',
        desc: "Chamada de sistema - exibe no console 'Volta 1'",
        vars: { vezes: 3, soma: 0, i: 1 },
        output: "Volta 1",
      },
      {
        line: 6,
        action: "soma = soma + i (soma = 0 + 1)",
        desc: "ALU soma valores. Resultado 1 armazenado em 'soma'",
        vars: { vezes: 3, soma: 1, i: 1 },
      },
      {
        line: 7,
        action: "Fim do corpo do loop, volta para o FOR",
        desc: "Processador encontra '}' e volta para linha 4",
        vars: { vezes: 3, soma: 1, i: 1 },
      },
      {
        line: 4,
        action: "i++ (incremento)",
        desc: "i = i + 1 → i agora é 2",
        vars: { vezes: 3, soma: 1, i: 2 },
      },
      {
        line: 4,
        action: "Teste i <= vezes? (2 <= 3)",
        desc: "Comparação: VERDADEIRO → executa loop novamente",
        vars: { vezes: 3, soma: 1, i: 2 },
      },
      {
        line: 5,
        action: 'printf("Volta 2\\n")',
        desc: "Exibe 'Volta 2' no console",
        vars: { vezes: 3, soma: 1, i: 2 },
        output: "Volta 2",
      },
      {
        line: 6,
        action: "soma = soma + i (soma = 1 + 2)",
        desc: "ALU: 1 + 2 = 3. 'soma' agora vale 3",
        vars: { vezes: 3, soma: 3, i: 2 },
      },
      {
        line: 7,
        action: "Volta para o FOR",
        desc: "Fim do corpo, retorna para linha 4",
        vars: { vezes: 3, soma: 3, i: 2 },
      },
      {
        line: 4,
        action: "i++ (incremento)",
        desc: "i = 2 + 1 → i agora é 3",
        vars: { vezes: 3, soma: 3, i: 3 },
      },
      {
        line: 4,
        action: "Teste i <= vezes? (3 <= 3)",
        desc: "Comparação: VERDADEIRO → executa mais uma vez",
        vars: { vezes: 3, soma: 3, i: 3 },
      },
      {
        line: 5,
        action: 'printf("Volta 3\\n")',
        desc: "Exibe 'Volta 3' no console",
        vars: { vezes: 3, soma: 3, i: 3 },
        output: "Volta 3",
      },
      {
        line: 6,
        action: "soma = soma + i (soma = 3 + 3)",
        desc: "ALU: 3 + 3 = 6. 'soma' agora vale 6",
        vars: { vezes: 3, soma: 6, i: 3 },
      },
      {
        line: 7,
        action: "Volta para o FOR",
        desc: "Fim do corpo, retorna para linha 4",
        vars: { vezes: 3, soma: 6, i: 3 },
      },
      {
        line: 4,
        action: "i++ (incremento)",
        desc: "i = 3 + 1 → i agora é 4",
        vars: { vezes: 3, soma: 6, i: 4 },
      },
      {
        line: 4,
        action: "Teste i <= vezes? (4 <= 3)",
        desc: "Comparação: FALSO → Sai do loop",
        vars: { vezes: 3, soma: 6, i: 4 },
      },
      {
        line: 8,
        action: "Pula linha em branco",
        desc: "Processador avança",
        vars: { vezes: 3, soma: 6, i: 4 },
      },
      {
        line: 9,
        action: 'printf("Soma total: 6\\n")',
        desc: "Exibe resultado final",
        vars: { vezes: 3, soma: 6, i: 4 },
        output: "Soma total: 6",
      },
      {
        line: 11,
        action: "return soma (return 6)",
        desc: "Função retorna valor 6 para quem chamou",
        vars: { vezes: 3, soma: 6, i: 4, resultado: 6 },
      },
      {
        line: 11,
        action: "FIM DA EXECUÇÃO",
        desc: "Processador termina. Programa finalizado!",
        vars: { vezes: 3, soma: 6, i: 4, resultado: 6 },
      },
    ],
  },
  factorial: {
    name: "Fatorial",
    codeLines: [
      "1   int n = 5;",
      "2   int resultado = 1;",
      "3   ",
      "4   for(int i = 1; i <= n; i++) {",
      '5       printf("Multiplicando por %d\\n", i);',
      "6       resultado = resultado * i;",
      "7   }",
      "8   ",
      '9   printf("Fatorial de %d é %d\\n", n, resultado);',
      "10  ",
      "11  return resultado;",
    ],
    steps: [
      {
        line: 0,
        action: "int n = 5;",
        desc: "Declara variável 'n' e inicializa com 5",
        vars: { n: 5 },
      },
      {
        line: 1,
        action: "int resultado = 1;",
        desc: "Declara variável 'resultado' e inicializa com 1",
        vars: { n: 5, resultado: 1 },
      },
      {
        line: 3,
        action: "Preparando loop FOR",
        desc: "Avalia condição inicial do loop",
        vars: { n: 5, resultado: 1, i: null },
      },
      {
        line: 4,
        action: "i = 1",
        desc: "Inicializa contador i com 1",
        vars: { n: 5, resultado: 1, i: 1 },
      },
      {
        line: 4,
        action: "Teste i <= n? (1 <= 5)",
        desc: "VERDADEIRO → entra no loop",
        vars: { n: 5, resultado: 1, i: 1 },
      },
      {
        line: 5,
        action: 'printf("Multiplicando por 1\\n")',
        desc: "Exibe mensagem",
        vars: { n: 5, resultado: 1, i: 1 },
        output: "Multiplicando por 1",
      },
      {
        line: 6,
        action: "resultado = 1 * 1",
        desc: "Multiplica resultado por i",
        vars: { n: 5, resultado: 1, i: 1 },
      },
      {
        line: 7,
        action: "Fim do loop, volta",
        desc: "Retorna para linha 4",
        vars: { n: 5, resultado: 1, i: 1 },
      },
      {
        line: 4,
        action: "i++",
        desc: "Incrementa i para 2",
        vars: { n: 5, resultado: 1, i: 2 },
      },
      {
        line: 4,
        action: "Teste i <= n? (2 <= 5)",
        desc: "VERDADEIRO",
        vars: { n: 5, resultado: 1, i: 2 },
      },
      {
        line: 5,
        action: 'printf("Multiplicando por 2\\n")',
        desc: "Exibe mensagem",
        vars: { n: 5, resultado: 1, i: 2 },
        output: "Multiplicando por 2",
      },
      {
        line: 6,
        action: "resultado = 1 * 2",
        desc: "resultado = 2",
        vars: { n: 5, resultado: 2, i: 2 },
      },
      {
        line: 7,
        action: "Volta",
        desc: "",
        vars: { n: 5, resultado: 2, i: 2 },
      },
      {
        line: 4,
        action: "i++",
        desc: "i = 3",
        vars: { n: 5, resultado: 2, i: 3 },
      },
      {
        line: 4,
        action: "Teste 3 <= 5",
        desc: "VERDADEIRO",
        vars: { n: 5, resultado: 2, i: 3 },
      },
      {
        line: 5,
        action: 'printf("Multiplicando por 3\\n")',
        desc: "",
        vars: { n: 5, resultado: 2, i: 3 },
        output: "Multiplicando por 3",
      },
      {
        line: 6,
        action: "resultado = 2 * 3",
        desc: "resultado = 6",
        vars: { n: 5, resultado: 6, i: 3 },
      },
      { line: 7, action: "", desc: "", vars: { n: 5, resultado: 6, i: 3 } },
      {
        line: 4,
        action: "i++",
        desc: "i = 4",
        vars: { n: 5, resultado: 6, i: 4 },
      },
      {
        line: 4,
        action: "Teste 4 <= 5",
        desc: "VERDADEIRO",
        vars: { n: 5, resultado: 6, i: 4 },
      },
      {
        line: 5,
        action: 'printf("Multiplicando por 4\\n")',
        desc: "",
        vars: { n: 5, resultado: 6, i: 4 },
        output: "Multiplicando por 4",
      },
      {
        line: 6,
        action: "resultado = 6 * 4",
        desc: "resultado = 24",
        vars: { n: 5, resultado: 24, i: 4 },
      },
      { line: 7, action: "", desc: "", vars: { n: 5, resultado: 24, i: 4 } },
      {
        line: 4,
        action: "i++",
        desc: "i = 5",
        vars: { n: 5, resultado: 24, i: 5 },
      },
      {
        line: 4,
        action: "Teste 5 <= 5",
        desc: "VERDADEIRO",
        vars: { n: 5, resultado: 24, i: 5 },
      },
      {
        line: 5,
        action: 'printf("Multiplicando por 5\\n")',
        desc: "",
        vars: { n: 5, resultado: 24, i: 5 },
        output: "Multiplicando por 5",
      },
      {
        line: 6,
        action: "resultado = 24 * 5",
        desc: "resultado = 120",
        vars: { n: 5, resultado: 120, i: 5 },
      },
      { line: 7, action: "", desc: "", vars: { n: 5, resultado: 120, i: 5 } },
      {
        line: 4,
        action: "i++",
        desc: "i = 6",
        vars: { n: 5, resultado: 120, i: 6 },
      },
      {
        line: 4,
        action: "Teste 6 <= 5",
        desc: "FALSO → sai do loop",
        vars: { n: 5, resultado: 120, i: 6 },
      },
      {
        line: 9,
        action: 'printf("Fatorial de 5 é 120\\n")',
        desc: "Exibe resultado",
        vars: { n: 5, resultado: 120, i: 6 },
        output: "Fatorial de 5 é 120",
      },
      {
        line: 11,
        action: "return 120",
        desc: "Retorna o resultado",
        vars: { n: 5, resultado: 120, i: 6 },
      },
      {
        line: 11,
        action: "FIM",
        desc: "Programa finalizado",
        vars: { n: 5, resultado: 120, i: 6 },
      },
    ],
  },
  fibonacci: {
    name: "Fibonacci",
    codeLines: [
      "1   int n = 5;",
      "2   int a = 0, b = 1;",
      "3   ",
      '4   printf("Sequência Fibonacci:\\n");',
      '5   printf("%d\\n", a);',
      '6   printf("%d\\n", b);',
      "7   ",
      "8   for(int i = 2; i < n; i++) {",
      "9       int temp = a + b;",
      '10      printf("%d\\n", temp);',
      "11      a = b;",
      "12      b = temp;",
      "13  }",
      "14  ",
      "15  return b;",
    ],
    steps: [
      {
        line: 0,
        action: "int n = 5;",
        desc: "Define limite da sequência",
        vars: { n: 5 },
      },
      {
        line: 1,
        action: "int a = 0, b = 1;",
        desc: "Inicializa primeiros termos",
        vars: { n: 5, a: 0, b: 1 },
      },
      {
        line: 4,
        action: 'printf("Sequência Fibonacci:\\n")',
        desc: "Cabeçalho",
        vars: { n: 5, a: 0, b: 1 },
        output: "Sequência Fibonacci:",
      },
      {
        line: 5,
        action: 'printf("%d\\n", a)',
        desc: "Primeiro termo",
        vars: { n: 5, a: 0, b: 1 },
        output: "0",
      },
      {
        line: 6,
        action: 'printf("%d\\n", b)',
        desc: "Segundo termo",
        vars: { n: 5, a: 0, b: 1 },
        output: "1",
      },
      {
        line: 8,
        action: "for(int i = 2; i < n; i++)",
        desc: "Loop para próximos termos",
        vars: { n: 5, a: 0, b: 1, i: 2 },
      },
      {
        line: 9,
        action: "temp = 0 + 1",
        desc: "Calcula próximo termo",
        vars: { n: 5, a: 0, b: 1, i: 2, temp: 1 },
      },
      {
        line: 10,
        action: 'printf("%d\\n", temp)',
        desc: "Exibe 1",
        vars: { n: 5, a: 0, b: 1, i: 2, temp: 1 },
        output: "1",
      },
      {
        line: 11,
        action: "a = b",
        desc: "Atualiza a",
        vars: { n: 5, a: 1, b: 1, i: 2, temp: 1 },
      },
      {
        line: 12,
        action: "b = temp",
        desc: "Atualiza b",
        vars: { n: 5, a: 1, b: 1, i: 2, temp: 1 },
      },
      {
        line: 8,
        action: "i++",
        desc: "Incrementa i",
        vars: { n: 5, a: 1, b: 1, i: 3 },
      },
      {
        line: 8,
        action: "i < n? (3 < 5)",
        desc: "VERDADEIRO",
        vars: { n: 5, a: 1, b: 1, i: 3 },
      },
      {
        line: 9,
        action: "temp = 1 + 1",
        desc: "temp = 2",
        vars: { n: 5, a: 1, b: 1, i: 3, temp: 2 },
      },
      {
        line: 10,
        action: 'printf("%d\\n", temp)',
        desc: "Exibe 2",
        vars: { n: 5, a: 1, b: 1, i: 3, temp: 2 },
        output: "2",
      },
      {
        line: 11,
        action: "a = 1",
        desc: "",
        vars: { n: 5, a: 1, b: 2, i: 3, temp: 2 },
      },
      {
        line: 12,
        action: "b = 2",
        desc: "",
        vars: { n: 5, a: 1, b: 2, i: 3, temp: 2 },
      },
      {
        line: 8,
        action: "i++",
        desc: "i = 4",
        vars: { n: 5, a: 1, b: 2, i: 4 },
      },
      {
        line: 8,
        action: "4 < 5",
        desc: "VERDADEIRO",
        vars: { n: 5, a: 1, b: 2, i: 4 },
      },
      {
        line: 9,
        action: "temp = 1 + 2",
        desc: "temp = 3",
        vars: { n: 5, a: 1, b: 2, i: 4, temp: 3 },
      },
      {
        line: 10,
        action: 'printf("%d\\n", temp)',
        desc: "Exibe 3",
        vars: { n: 5, a: 1, b: 2, i: 4, temp: 3 },
        output: "3",
      },
      {
        line: 11,
        action: "a = 2",
        desc: "",
        vars: { n: 5, a: 2, b: 3, i: 4, temp: 3 },
      },
      {
        line: 12,
        action: "b = 3",
        desc: "",
        vars: { n: 5, a: 2, b: 3, i: 4, temp: 3 },
      },
      {
        line: 8,
        action: "i++",
        desc: "i = 5",
        vars: { n: 5, a: 2, b: 3, i: 5 },
      },
      {
        line: 8,
        action: "5 < 5",
        desc: "FALSO → sai",
        vars: { n: 5, a: 2, b: 3, i: 5 },
      },
      {
        line: 15,
        action: "return b",
        desc: "Retorna último termo",
        vars: { n: 5, a: 2, b: 3, i: 5 },
      },
      { line: 15, action: "FIM", desc: "", vars: { n: 5, a: 2, b: 3, i: 5 } },
    ],
  },
  maxArray: {
    name: "Máximo em Array",
    codeLines: [
      "1   int arr[] = {3, 7, 2, 9, 5};",
      "2   int max = arr[0];",
      "3   ",
      "4   for(int i = 1; i < 5; i++) {",
      "5       if(arr[i] > max) {",
      "6           max = arr[i];",
      "7       }",
      "8   }",
      "9   ",
      '10  printf("Máximo: %d\\n", max);',
      "11  ",
      "12  return max;",
    ],
    steps: [
      {
        line: 0,
        action: "int arr[] = {3,7,2,9,5};",
        desc: "Inicializa array na memória",
        vars: { arr: [3, 7, 2, 9, 5] },
      },
      {
        line: 1,
        action: "int max = arr[0];",
        desc: "max = 3",
        vars: { arr: [3, 7, 2, 9, 5], max: 3 },
      },
      {
        line: 4,
        action: "for(int i = 1; i < 5; i++)",
        desc: "Loop para verificar elementos",
        vars: { arr: [3, 7, 2, 9, 5], max: 3, i: 1 },
      },
      {
        line: 5,
        action: "if(arr[1] > max) (7 > 3)",
        desc: "VERDADEIRO → entra if",
        vars: { arr: [3, 7, 2, 9, 5], max: 3, i: 1 },
      },
      {
        line: 6,
        action: "max = arr[1]",
        desc: "max = 7",
        vars: { arr: [3, 7, 2, 9, 5], max: 7, i: 1 },
      },
      {
        line: 8,
        action: "Fim if, volta loop",
        desc: "",
        vars: { arr: [3, 7, 2, 9, 5], max: 7, i: 1 },
      },
      {
        line: 4,
        action: "i++",
        desc: "i = 2",
        vars: { arr: [3, 7, 2, 9, 5], max: 7, i: 2 },
      },
      {
        line: 4,
        action: "i < 5? (2 < 5)",
        desc: "VERDADEIRO",
        vars: { arr: [3, 7, 2, 9, 5], max: 7, i: 2 },
      },
      {
        line: 5,
        action: "if(arr[2] > max) (2 > 7)",
        desc: "FALSO → pula if",
        vars: { arr: [3, 7, 2, 9, 5], max: 7, i: 2 },
      },
      {
        line: 8,
        action: "Volta loop",
        desc: "",
        vars: { arr: [3, 7, 2, 9, 5], max: 7, i: 2 },
      },
      {
        line: 4,
        action: "i++",
        desc: "i = 3",
        vars: { arr: [3, 7, 2, 9, 5], max: 7, i: 3 },
      },
      {
        line: 4,
        action: "3 < 5",
        desc: "VERDADEIRO",
        vars: { arr: [3, 7, 2, 9, 5], max: 7, i: 3 },
      },
      {
        line: 5,
        action: "if(arr[3] > max) (9 > 7)",
        desc: "VERDADEIRO",
        vars: { arr: [3, 7, 2, 9, 5], max: 7, i: 3 },
      },
      {
        line: 6,
        action: "max = arr[3]",
        desc: "max = 9",
        vars: { arr: [3, 7, 2, 9, 5], max: 9, i: 3 },
      },
      {
        line: 8,
        action: "",
        desc: "",
        vars: { arr: [3, 7, 2, 9, 5], max: 9, i: 3 },
      },
      {
        line: 4,
        action: "i++",
        desc: "i = 4",
        vars: { arr: [3, 7, 2, 9, 5], max: 9, i: 4 },
      },
      {
        line: 4,
        action: "4 < 5",
        desc: "VERDADEIRO",
        vars: { arr: [3, 7, 2, 9, 5], max: 9, i: 4 },
      },
      {
        line: 5,
        action: "if(arr[4] > max) (5 > 9)",
        desc: "FALSO",
        vars: { arr: [3, 7, 2, 9, 5], max: 9, i: 4 },
      },
      {
        line: 8,
        action: "",
        desc: "",
        vars: { arr: [3, 7, 2, 9, 5], max: 9, i: 4 },
      },
      {
        line: 4,
        action: "i++",
        desc: "i = 5",
        vars: { arr: [3, 7, 2, 9, 5], max: 9, i: 5 },
      },
      {
        line: 4,
        action: "5 < 5",
        desc: "FALSO → sai loop",
        vars: { arr: [3, 7, 2, 9, 5], max: 9, i: 5 },
      },
      {
        line: 10,
        action: 'printf("Máximo: 9\\n")',
        desc: "Exibe resultado",
        vars: { arr: [3, 7, 2, 9, 5], max: 9, i: 5 },
        output: "Máximo: 9",
      },
      {
        line: 12,
        action: "return 9",
        desc: "Retorna máximo",
        vars: { arr: [3, 7, 2, 9, 5], max: 9, i: 5 },
      },
      {
        line: 12,
        action: "FIM",
        desc: "",
        vars: { arr: [3, 7, 2, 9, 5], max: 9, i: 5 },
      },
    ],
  },
};
